.circleci/config.yml, package.json, src/pages/invoice.js, src/server/lib/graphql.js, src/server/routes.js, test/__fixtures__/invoices/transactions-with-tax.json, test/pages/__snapshots__/invoice.test.js.snap, test/pages/invoice.test.js
=> Add support for taxes

README.md, src/lib/utils.js, src/pages/index.js, src/pages/invoice.js, src/server/controllers/transactions.js, src/server/routes.js, test/__fixtures__/invoices/organization-gift-cards.json, test/pages/__snapshots__/invoice.test.js.snap
This new page will make testing and developing easier than ever. We can now benefit from auto-reload when developing invoices.
Demo: https://opencollective-invoices-nepqplbglt.now.sh/
=> Revamp test page

src/pages/invoice.js, test/pages/__snapshots__/invoice.test.js.snap
Fix https://github.com/opencollective/opencollective/issues/1838
=> Limit the number of transactions on first page

src/pages/invoice.js, test/pages/__snapshots__/invoice.test.js.snap
Following a feedback from @xdamman 
**Before**
**After**
=> Left align user email address

src/components/LinkToCollective.js, src/pages/invoice.js, src/server/lib/graphql.js, test/pages/__snapshots__/invoice.test.js.snap
@piamancini This follow the recommendation you made during the invoices redesign demo. I removed the user link from the description for transactions with gift cards. Should I remove the icon as well?
=> Remove gift card user from transaction description

src/server/controllers/transactions.js, src/server/routes.js
Since https://github.com/opencollective/opencollective-invoices/pull/30 we use a new endpoint
=> chore: Remove derecated endpoint

src/pages/invoice.js
handling : https://github.com/opencollective/opencollective/issues/2591
@znarf : Easy fix :robot:
=> fix:2591 - Display correct date on invoice

src/server/controllers/transactions.js, src/server/lib/graphql.js
Together with https://github.com/opencollective/opencollective-api/pull/3131, resolve https://github.com/opencollective/opencollective-api/pull/3131
=> Add token for fetching transaction invoice

.babelrc, src/pages/_app.js
Remove deprecated NextJS container and fix broken build
=> Update build config

src/server/controllers/transactions.js
We had multiple users clicking on the deprecated links in old emails for transaction receipt after new years eve (probably they needed them for 2019 accountability?). This implements a more helpful error message that explains where to go to get the invoice.
=> Transaction Invoice: Improve error message

.gitignore, src/lib/withIntl.js
- Fix broken build after react-intl update
=> Improve build

.eslintrc, components/LinkToCollective.js, components/Receipt.js, lib/utils.js, pages/[collectiveSlug]/transactions/[transactionUuid]/[filename].js, pages/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate].js, pages/fixtures/[fixture].js, pages/status.pdf.js
=> Fix ESlint warnings

components/CollectiveFooter.js, components/ExpenseAttachmentsTable.js, components/ExpenseInvoice.js, components/LinkToCollective.js, components/Receipt.js, lib/graphql/queries.js, lib/req-utils.js, lib/utils.js, pages/expense/[id]/[filename].js
Part of https://github.com/opencollective/opencollective/issues/2944
Example: [Expense-2404-opensource-invoice.pdf](https://github.com/opencollective/opencollective-invoices/files/4313762/Expense-2404-opensource-invoice.pdf)
All the base info (collective, payee, attachments, `invoiceInfo`) are displayed.
=> Expense invoices

components/Receipt.js, lib/graphql/index.js, lib/graphql/queries.js
=> Add GraphQL fragment matcher

components/ExpenseInvoice.js, components/ExpenseItemsTable.js, lib/graphql/queries.js
Require https://github.com/opencollective/opencollective-api/pull/3671
Resolve https://github.com/opencollective/opencollective/issues/3039
=> Rename ExpenseAttachment to ExpenseItem

components/ExpenseInvoice.js, lib/graphql/queries.js
Require https://github.com/opencollective/opencollective-api/pull/3789
=> PayeeLocation: Fetch using new field

components/CustomIntlDate.js, components/Receipt.js
This changes the dates within the transaction pdf to intl standard.
Fixes https://github.com/opencollective/opencollective/issues/3096
=> Change Dates Within the Transaction PDF to Intl Standard

components/CollectiveAddress.js
Fix https://github.com/opencollective/opencollective/issues/3359
=> CollectiveAddress: Use en as default locale

package.json
=> docs(package.json): Remove deploy cmds

pages/_document.js, pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js, pages/receipts/transactions/[uuid]/[filename].js
Enable the new endpoints described in https://github.com/opencollective/opencollective/issues/2959
=> Receipts: Enable new endpoints

components/CollectiveFooter.js, components/ReceiptV2.js, lib/graphql/queries.js, lib/transactions.js, pages/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate].js, pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js
Require https://github.com/opencollective/opencollective-api/pull/4563
Resolve https://github.com/opencollective/opencollective/issues/3486
- Move the receipt by date range endpoint to GQLV2
- Include incognito contributions
---
=> Receipts: Include incognito transactions

components/Receipt.js, components/ReceiptV2.js, lib/fixtures/donation-receipt.json, lib/fixtures/organization-gift-cards-monthly.json, lib/fixtures/organization-gift-cards-yearly.json, lib/fixtures/simple-transaction.json, lib/fixtures/transactions-with-date-range.json, lib/fixtures/transactions-with-tax.json, lib/graphql/fragments.js, public/static/fixtures/simple-transaction-with-vat.json
Require https://github.com/opencollective/opencollective-api/pull/5252
=> Rename Virtual Cards to Gift Cards

.github/workflows/ci.yml, CONTRIBUTING.md, SECURITY.md
Related to https://github.com/opencollective/opencollective/issues/3675
=> Rename `master` to `main`

components/ReceiptV2.js, lib/graphql/queries.js
Fix https://github.com/opencollective/opencollective/issues/4156
=> Receipt: Show proper currency

.github/workflows/ci.yml
Related to https://github.com/opencollective/opencollective/issues/4207
=> Add support for running workflows without restriction for dependabot

.github/workflows/ci.yml
Related to https://github.com/opencollective/opencollective/issues/4207
Resolves the issue mentioned in, https://github.com/opencollective/opencollective-api/pull/5895#issuecomment-825621778
=> Point to the correct branch in the checkout action when using dependabot

.github/ISSUE_TEMPLATE/config.yml
https://github.com/opencollective/opencollective/issues/4375
=> Add `config.yml` for Issue Templates

renovate.json
Related to https://github.com/opencollective/opencollective/issues/4243
=> Add centralized renovate config

components/ReceiptV2.js, lib/transactions.js
To prepare the changes related to https://github.com/opencollective/opencollective/issues/4361
=> Use Math.abs when handling taxAmount

lib/graphql/queries.js
Require https://github.com/opencollective/opencollective-frontend/pull/6511
=> Use DateTime GraphQL type

lib/graphql/queries.js
Fix https://github.com/opencollective/opencollective/issues/4570
=> ExpenseInvoice: Fetch host for funds

components/AccountName.js, components/ExpenseInvoice.js, components/LinkToCollective.js, components/Receipt.js, components/ReceiptV2.js, lib/graphql/fragments.js, lib/graphql/queries.js
Resolve https://github.com/opencollective/opencollective/issues/4582
Displayed in the form of `Legal Name (Name)`
=> Introduce legal name

lib/graphql/queries.js
Also use a proper GQL tag for prettier to do its job
=> Add `includeGiftCardTransactions` flag

lib/graphql/fragments.js, pages/receipts/transactions/[uuid]/[filename].js
For https://github.com/opencollective/opencollective-api/pull/6575
=> TransactionReceipt: Remove deprecated fields from query

pages/index.js
Resolve https://github.com/opencollective/opencollective/issues/4919
=> Only allow internal URLs for test page

components/Receipt.js, components/ReceiptV2.js, lib/graphql/queries.js
Fix https://github.com/opencollective/opencollective/issues/5495
=> Always use payer's host as billTo

components/Receipt.js, components/ReceiptV2.js, lib/graphql/queries.js
Require https://github.com/opencollective/opencollective-api/pull/7607
Fix https://github.com/opencollective/opencollective/issues/5608
=> Use generic legal name for all accounts

.gitignore
Make sure we account for other `.env` files such as `.env.staging`, `.env.local` etc.
=> Add all environment variable files to gitignore

components/Receipt.js, components/ReceiptV2.js, lib/fixtures/organization-gift-cards-monthly.json, lib/fixtures/organization-gift-cards-yearly.json, lib/fixtures/simple-transaction.json, lib/fixtures/transactions-with-tax.json, lib/graphql/queries.js, pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js, pages/receipts/transactions/[uuid]/[filename].js, public/static/fixtures/simple-transaction-with-vat.json
Related to https://github.com/opencollective/opencollective/issues/5368
Related Front-end PR: https://github.com/opencollective/opencollective-frontend/pull/7985
Related API PR: https://github.com/opencollective/opencollective-api/pull/7709
=>  Add support for receipt templates (for non-tax deductible payments)

components/CollectiveAddress.js, components/ExpenseInvoice.js, lib/graphql/queries.js
Goes with https://github.com/opencollective/opencollective-frontend/pull/8053
=> Use host config for Expense invoice's Bill To

components/Receipt.js, lib/graphql/queries.js
Context:
https://opencollective.slack.com/archives/C6JTTA4SK/p1663435610713949
=> Include Payment Method to single transaction receipt

README.md
Resolves https://github.com/opencollective/opencollective/issues/6267
=> Personal token follow up: Update README.md

components/Receipt.js
Resolve https://github.com/opencollective/opencollective/issues/5171
=> Misc improvements for refunds

components/Receipt.js, lib/graphql/queries.js
https://github.com/opencollective/opencollective/issues/6571
=> Show contribution ID on Receipt

components/Receipt.js, lib/graphql/queries.js
Removed in https://github.com/opencollective/opencollective-pdf/pull/912
=> Receipt: add payment method back

pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js, pages/receipts/transactions/[id]/[filename].js
Fix https://github.com/opencollective/opencollective/issues/6945
=> Fix alternative receipt templates

components/ExpenseInvoice.js, components/ExpenseItemsTable.js, lib/constants/currency.js, lib/expenses.js, lib/graphql/queries.js, lib/utils.js
Part of https://github.com/opencollective/opencollective/issues/7010
Require https://github.com/opencollective/opencollective-api/pull/9529
=> Expense: add support for item currency

lib/graphql/queries.js, pages/receipts/transactions/[id]/[filename].js
Fixes an issue introduced in https://github.com/opencollective/opencollective-pdf/pull/973
=> Receipt: fix "bill to" with host

lib/errors.js, lib/graphql/queries.js, lib/req-utils.js, pages/_document.js, pages/expense/[id]/[filename].js, pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js, pages/receipts/transactions/[id]/[filename].js
Require https://github.com/opencollective/opencollective-api/pull/9864
- Return properly formatted JSON errors with the matching HTTP code (based on API's response)
- Throw permission errors when not allowed to access a resource
- Fix authentication parameters not working when provided from query parameters
=> Permissions & error handling

lib/pdf-lib-utils.ts, pages/api/tax-form/[filename].ts
Resolve https://github.com/opencollective/opencollective/issues/7390
=> Tax Form: add watermark if non final

lib/i18n.ts, lib/tax-forms/w9.ts
For https://opencollective.slack.com/archives/D014W1CE5P0/p1720040249155959
=> enhancement(TaxForms): surface country on W9

components/Receipt.js, lib/graphql/queries.js, pages/receipts/transactions/[id]/[filename].js
Fix https://github.com/opencollective/opencollective/issues/7537#issuecomment-2328018331
=> fix(Receipt): adapt for refunds

components/ExpenseInvoice.js, lib/graphql/queries.js
Require https://github.com/opencollective/opencollective-api/pull/10297
Part of https://github.com/opencollective/opencollective/issues/7531
=> feat(Expense): add reference

lib/pdf-lib-utils.ts, lib/tax-forms/w8-ben-e.ts
Fix https://oficonsortium.slack.com/archives/GFH4N961L/p1730220591360379
> I filled out the Tax Form but I noticed that some of the info that I put in your website form were not updated in the document. For instances, you ask if the company is active or passive, I chose active. But the checkbox for it, in Part I section V is not marked in the document. Also the part XXV. Could you please check if there is anything wrong?
=> fix(TaxForm): handling of NFFE status

lib/tax-forms/w8-ben.ts
For https://oficonsortium.slack.com/archives/GFH4N961L/p1733419924724549a
Goes wiht https://github.com/opencollective/opencollective-frontend/pull/10860
=> fix(TaxForms): use residency country for chapter 3
