opencollective/opencollective-pdf

package.json
src/pages/invoice.js
src/server/controllers/transactions.js
src/server/lib/graphql.js
src/server/routes.js
test/__fixtures__/invoices/organization-gift-cards-monthly.json
test/__fixtures__/invoices/organization-gift-cards-yearly.json
test/__fixtures__/invoices/transactions-with-date-range.json
test/pages/__snapshots__/invoice.test.js.snap
test/pages/invoice.test.js

This adds a new route:
```
'/collectives/:fromCollectiveSlug/:toCollectiveSlug/:isoStartDate/:isoEndDate.:format(html|pdf|json)',
```
And updates the `invoice` template to:
- render  from and to dates when applicable
- use a different invoice reference format for invoices with a date range. The new format is: `${invoice.host.slug}_${invoice.fromCollective.slug}_${startString}-${endString}`

Consolidated yearly invoice #1783 

---

src/server/controllers/transactions.js
src/server/lib/graphql.js

Require https://github.com/opencollective/opencollective-api/pull/1940
Removes authentication check for transaction invoice that was breaking links sent by email. We consider `uuid` to be private, so the check was redundant.

chore(TransactionInvoice): Remove authentication check

---

pages/_document.js

Prior to this PR, errors were returned as content body. So error messages were embed inside of PDF.
With this PR, any error will be returned as JSON to be parsed and handled by frontend.

Return errors as JSON

---

pages/transactions/[transactionUuid]/[filename].js

Removes the `/:collective/transactions/:uuid/invoice.pdf` route that is not used anymore.
Restores the `/transactions/:uuid/invoice.pdf` route that was mistakenly removed in https://github.com/opencollective/opencollective-invoices/pull/267

TransactionInvoice: Remove collective from default route

---

pages/[collectiveSlug]/transactions/[:uuid]/[filename].js
pages/transactions/[transactionUuid]/[filename].js

Because if people click on a link sent in an old email, it still nice for them to have a nice message telling them what to do rather than contacting support.

TransactionInvoice: Add fallback message for old URL

---

lib/req-utils.js
pages/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate].js

Frontend sends `OPTIONS` requests without `authorization`, and we must not fail in such cases. It's API's responsibility to check for authentication.

Accept requests without autorization header

---

pages/_document.js

Frontend sends an OPTIONS request to check CORS, but it doesn't have an `authorization` header. Also we don't want to generate the PDF two times when that happens, so we just return OK.

Ignore OPTIONS requests

---

components/Receipt.js
lib/graphql/fragments.js

Related to https://github.com/opencollective/opencollective/issues/2743
This PR adds a user's name on the invoice for incognito transactions

Show user name on invoice for incognito transactions

---

components/Receipt.js
lib/fixtures/donation-receipt.json
lib/fixtures/organization-gift-cards-monthly.json

Following up on https://github.com/opencollective/opencollective-pdf/pull/260
- Only display extraInfo on last page (and not on all pages)
- Improve text style and position

Receipt: Only display extraInfo on last page

---

components/Receipt.js
lib/fixtures/donation-receipt.json
lib/fixtures/organization-gift-cards-monthly.json
lib/fixtures/organization-gift-cards-yearly.json
lib/fixtures/transactions-with-date-range.json
lib/fixtures/transactions-with-tax.json
lib/graphql/fragments.js
public/static/fixtures/simple-transaction-with-vat.json

Resolves https://github.com/opencollective/opencollective/issues/2931
This PR adds the VAT number to receipts when `orders` don't contain a user's tax number.

chore: add VAT number in receipts

---

README.md

CircleCI is removed and replaced by GitHub Actions. Therefore the badge should be updated. :smile_cat:

Remove CircleCI badge and add GitHub Actions badge

---

lib/constants/account-type.js
lib/graphql/queries.js
pages/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate].js

Follows up https://github.com/opencollective/opencollective-api/pull/5202 to resolve https://github.com/opencollective/opencollective/issues/3684
- For organizations, transactions to self i.e where `transaction.fromAccount.id === transaction.toAccount.id` should not appear in payment receipts 
- For an individual, transactions with `DEBIT` type, usually an expense transaction should not appear in payment receipts.

fix(paymentReceipts): prevent expense transactions and self-transactions from payments receipts

---

.github/workflows/ci.yml

The CI now runs fine but when doing pull requests after, https://github.com/opencollective/opencollective-api/pull/5895 but there's a certain case where opening a PR from another branch can duplicate of the CI runs (example: https://github.com/opencollective/opencollective-api/pull/5901). This PR takes care of that. 
Related to https://github.com/opencollective/opencollective/issues/4207

Addition of `if` conditions to make sure ci runs are not duplicated

---

.github/dependabot.yml
.github/workflows/ci.yml

Reverts opencollective/opencollective-pdf#669
Reverting this one as we ended up without dependabot on this repo, while I don't think it caused any trouble here? Plus, I don't see it on https://app.dependabot.com/accounts/opencollective and thus I'm not sure whether it's still possible to add it back this way.

Revert "Remove dependabot.yml so that we can migrate to v1"

---

pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js

Broken in https://github.com/opencollective/opencollective-frontend/pull/6511, parsing is not accepting values like `2021-06-30T23:59:59` anymore, the full `2021-06-30T23:59:59.999Z` is needed.

Receipts: Fix `dateTo` parsing

---

components/AccountName.js

See #765 and #774
(AFAIK providing a legal name is quite new)
If I enter a legal name, why would I want to see the account name (which is the "display name" and can be some random name) as well on a document e.g. invoice? Isn't that the reason I just enter the legal name? Accounting, tax offices, etc. don't care what your name is on some internet plattform, they just care about the legal name. That's why I think that's when a legal name is provided, is the only thing that should be used, nothing else should be rendered.
BTW: You can achive that right now with a workaround by just going to the settings of a personal or organization account and just remove the account name. That works (see https://github.com/opencollective/opencollective/issues/5002), therefore the code I am changing in …

Just display "legalname" instead of "legalname (accountname)" on documents

---

README.md

Recently I was wondering how the pdf service gets deployed and asked @Betree about it. I think nice to add a small text to our readme for future reference and for anyone who comes across the same question. 😉

Add deployment details to readme

---

components/Receipt.js
components/ReceiptV2.js
lib/graphql/queries.js
lib/transactions.js
next.config.js
pages/expense/[id]/[filename].js
pages/receipts/collectives/[fromCollectiveSlug]/[toCollectiveSlug]/[isoStartDate]/[isoEndDate]/[filename].js
pages/receipts/transactions/[uuid]/[filename].js

Fix https://github.com/opencollective/opencollective/issues/5171
Require https://github.com/opencollective/opencollective-api/pull/8866
After https://github.com/opencollective/opencollective-pdf/pull/912, I want to improve that a bit and make sure all refunds are displayed as "$0" and not summed up.

Handle refunds in receipt

---

README.md

When I want to download a receipt I get an error without `PDF_SERVICE_URL=http://localhost:3002` line in `.env`.

Update "Usage with frontend" section

---

package-lock.json
package.json

Reverts opencollective/opencollective-pdf#1123
Many pingdom alerts with rate limit errors after merging this one. The rate limit seems to happen globally, for all IP addresses, as even requests from new IPs get blocked.

Revert "fix(deps): update dependency express-rate-limit to v8"
